// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: corkscrewdb.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CorkScrewDB_Info_FullMethodName             = "/corkscrewdb.transport.v1.CorkScrewDB/Info"
	CorkScrewDB_EnsureCollection_FullMethodName = "/corkscrewdb.transport.v1.CorkScrewDB/EnsureCollection"
	CorkScrewDB_DropCollection_FullMethodName   = "/corkscrewdb.transport.v1.CorkScrewDB/DropCollection"
	CorkScrewDB_Put_FullMethodName              = "/corkscrewdb.transport.v1.CorkScrewDB/Put"
	CorkScrewDB_PutVector_FullMethodName        = "/corkscrewdb.transport.v1.CorkScrewDB/PutVector"
	CorkScrewDB_Delete_FullMethodName           = "/corkscrewdb.transport.v1.CorkScrewDB/Delete"
	CorkScrewDB_Search_FullMethodName           = "/corkscrewdb.transport.v1.CorkScrewDB/Search"
	CorkScrewDB_SearchVector_FullMethodName     = "/corkscrewdb.transport.v1.CorkScrewDB/SearchVector"
	CorkScrewDB_History_FullMethodName          = "/corkscrewdb.transport.v1.CorkScrewDB/History"
	CorkScrewDB_PullEntries_FullMethodName      = "/corkscrewdb.transport.v1.CorkScrewDB/PullEntries"
	CorkScrewDB_PullSnapshot_FullMethodName     = "/corkscrewdb.transport.v1.CorkScrewDB/PullSnapshot"
	CorkScrewDB_PrepareRebalance_FullMethodName = "/corkscrewdb.transport.v1.CorkScrewDB/PrepareRebalance"
	CorkScrewDB_CommitRebalance_FullMethodName  = "/corkscrewdb.transport.v1.CorkScrewDB/CommitRebalance"
	CorkScrewDB_PruneRebalance_FullMethodName   = "/corkscrewdb.transport.v1.CorkScrewDB/PruneRebalance"
)

// CorkScrewDBClient is the client API for CorkScrewDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorkScrewDBClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	EnsureCollection(ctx context.Context, in *EnsureCollectionRequest, opts ...grpc.CallOption) (*Empty, error)
	DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*Empty, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Empty, error)
	PutVector(ctx context.Context, in *PutVectorRequest, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchVector(ctx context.Context, in *SearchVectorRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	PullEntries(ctx context.Context, in *PullEntriesRequest, opts ...grpc.CallOption) (*PullEntriesResponse, error)
	PullSnapshot(ctx context.Context, in *PullSnapshotRequest, opts ...grpc.CallOption) (*PullSnapshotResponse, error)
	PrepareRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error)
	CommitRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error)
	PruneRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error)
}

type corkScrewDBClient struct {
	cc grpc.ClientConnInterface
}

func NewCorkScrewDBClient(cc grpc.ClientConnInterface) CorkScrewDBClient {
	return &corkScrewDBClient{cc}
}

func (c *corkScrewDBClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) EnsureCollection(ctx context.Context, in *EnsureCollectionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_EnsureCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) PutVector(ctx context.Context, in *PutVectorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_PutVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) SearchVector(ctx context.Context, in *SearchVectorRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_SearchVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) PullEntries(ctx context.Context, in *PullEntriesRequest, opts ...grpc.CallOption) (*PullEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullEntriesResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_PullEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) PullSnapshot(ctx context.Context, in *PullSnapshotRequest, opts ...grpc.CallOption) (*PullSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullSnapshotResponse)
	err := c.cc.Invoke(ctx, CorkScrewDB_PullSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) PrepareRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_PrepareRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) CommitRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_CommitRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkScrewDBClient) PruneRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CorkScrewDB_PruneRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorkScrewDBServer is the server API for CorkScrewDB service.
// All implementations should embed UnimplementedCorkScrewDBServer
// for forward compatibility.
type CorkScrewDBServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	EnsureCollection(context.Context, *EnsureCollectionRequest) (*Empty, error)
	DropCollection(context.Context, *DropCollectionRequest) (*Empty, error)
	Put(context.Context, *PutRequest) (*Empty, error)
	PutVector(context.Context, *PutVectorRequest) (*Empty, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchVector(context.Context, *SearchVectorRequest) (*SearchResponse, error)
	History(context.Context, *HistoryRequest) (*HistoryResponse, error)
	PullEntries(context.Context, *PullEntriesRequest) (*PullEntriesResponse, error)
	PullSnapshot(context.Context, *PullSnapshotRequest) (*PullSnapshotResponse, error)
	PrepareRebalance(context.Context, *RebalanceRequest) (*Empty, error)
	CommitRebalance(context.Context, *RebalanceRequest) (*Empty, error)
	PruneRebalance(context.Context, *RebalanceRequest) (*Empty, error)
}

// UnimplementedCorkScrewDBServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorkScrewDBServer struct{}

func (UnimplementedCorkScrewDBServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedCorkScrewDBServer) EnsureCollection(context.Context, *EnsureCollectionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureCollection not implemented")
}
func (UnimplementedCorkScrewDBServer) DropCollection(context.Context, *DropCollectionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedCorkScrewDBServer) Put(context.Context, *PutRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedCorkScrewDBServer) PutVector(context.Context, *PutVectorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVector not implemented")
}
func (UnimplementedCorkScrewDBServer) Delete(context.Context, *DeleteRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCorkScrewDBServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCorkScrewDBServer) SearchVector(context.Context, *SearchVectorRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchVector not implemented")
}
func (UnimplementedCorkScrewDBServer) History(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedCorkScrewDBServer) PullEntries(context.Context, *PullEntriesRequest) (*PullEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullEntries not implemented")
}
func (UnimplementedCorkScrewDBServer) PullSnapshot(context.Context, *PullSnapshotRequest) (*PullSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullSnapshot not implemented")
}
func (UnimplementedCorkScrewDBServer) PrepareRebalance(context.Context, *RebalanceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareRebalance not implemented")
}
func (UnimplementedCorkScrewDBServer) CommitRebalance(context.Context, *RebalanceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitRebalance not implemented")
}
func (UnimplementedCorkScrewDBServer) PruneRebalance(context.Context, *RebalanceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneRebalance not implemented")
}
func (UnimplementedCorkScrewDBServer) testEmbeddedByValue() {}

// UnsafeCorkScrewDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorkScrewDBServer will
// result in compilation errors.
type UnsafeCorkScrewDBServer interface {
	mustEmbedUnimplementedCorkScrewDBServer()
}

func RegisterCorkScrewDBServer(s grpc.ServiceRegistrar, srv CorkScrewDBServer) {
	// If the following call pancis, it indicates UnimplementedCorkScrewDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CorkScrewDB_ServiceDesc, srv)
}

func _CorkScrewDB_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_EnsureCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).EnsureCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_EnsureCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).EnsureCollection(ctx, req.(*EnsureCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).DropCollection(ctx, req.(*DropCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_PutVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).PutVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_PutVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).PutVector(ctx, req.(*PutVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_SearchVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).SearchVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_SearchVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).SearchVector(ctx, req.(*SearchVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).History(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_PullEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).PullEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_PullEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).PullEntries(ctx, req.(*PullEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_PullSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).PullSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_PullSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).PullSnapshot(ctx, req.(*PullSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_PrepareRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).PrepareRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_PrepareRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).PrepareRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_CommitRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).CommitRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_CommitRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).CommitRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkScrewDB_PruneRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkScrewDBServer).PruneRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkScrewDB_PruneRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkScrewDBServer).PruneRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CorkScrewDB_ServiceDesc is the grpc.ServiceDesc for CorkScrewDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CorkScrewDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corkscrewdb.transport.v1.CorkScrewDB",
	HandlerType: (*CorkScrewDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _CorkScrewDB_Info_Handler,
		},
		{
			MethodName: "EnsureCollection",
			Handler:    _CorkScrewDB_EnsureCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _CorkScrewDB_DropCollection_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _CorkScrewDB_Put_Handler,
		},
		{
			MethodName: "PutVector",
			Handler:    _CorkScrewDB_PutVector_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CorkScrewDB_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _CorkScrewDB_Search_Handler,
		},
		{
			MethodName: "SearchVector",
			Handler:    _CorkScrewDB_SearchVector_Handler,
		},
		{
			MethodName: "History",
			Handler:    _CorkScrewDB_History_Handler,
		},
		{
			MethodName: "PullEntries",
			Handler:    _CorkScrewDB_PullEntries_Handler,
		},
		{
			MethodName: "PullSnapshot",
			Handler:    _CorkScrewDB_PullSnapshot_Handler,
		},
		{
			MethodName: "PrepareRebalance",
			Handler:    _CorkScrewDB_PrepareRebalance_Handler,
		},
		{
			MethodName: "CommitRebalance",
			Handler:    _CorkScrewDB_CommitRebalance_Handler,
		},
		{
			MethodName: "PruneRebalance",
			Handler:    _CorkScrewDB_PruneRebalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "corkscrewdb.proto",
}
