// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: corkscrewdb.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_corkscrewdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{0}
}

type EmbeddingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingConfig) Reset() {
	*x = EmbeddingConfig{}
	mi := &file_corkscrewdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingConfig) ProtoMessage() {}

func (x *EmbeddingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingConfig.ProtoReflect.Descriptor instead.
func (*EmbeddingConfig) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmbeddingConfig) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_corkscrewdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Entry) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Entry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_corkscrewdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_corkscrewdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LamportClock  uint64                 `protobuf:"varint,4,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	WallClock     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=wall_clock,json=wallClock,proto3" json:"wall_clock,omitempty"`
	Tombstone     bool                   `protobuf:"varint,7,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_corkscrewdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{5}
}

func (x *Version) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Version) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Version) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Version) GetLamportClock() uint64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *Version) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Version) GetWallClock() *timestamppb.Timestamp {
	if x != nil {
		return x.WallClock
	}
	return nil
}

func (x *Version) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{6}
}

func (x *InfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type InfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageVersion string                 `protobuf:"bytes,1,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	Embedding      *EmbeddingConfig       `protobuf:"bytes,2,opt,name=embedding,proto3" json:"embedding,omitempty"`
	Peers          []string               `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_corkscrewdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{7}
}

func (x *InfoResponse) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *InfoResponse) GetEmbedding() *EmbeddingConfig {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *InfoResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type EnsureCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BitWidth      int32                  `protobuf:"varint,3,opt,name=bit_width,json=bitWidth,proto3" json:"bit_width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCollectionRequest) Reset() {
	*x = EnsureCollectionRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCollectionRequest) ProtoMessage() {}

func (x *EnsureCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCollectionRequest.ProtoReflect.Descriptor instead.
func (*EnsureCollectionRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{8}
}

func (x *EnsureCollectionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnsureCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnsureCollectionRequest) GetBitWidth() int32 {
	if x != nil {
		return x.BitWidth
	}
	return 0
}

type DropCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{9}
}

func (x *DropCollectionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DropCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,5,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{10}
}

func (x *PutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PutRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *PutRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PutVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,5,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutVectorRequest) Reset() {
	*x = PutVectorRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVectorRequest) ProtoMessage() {}

func (x *PutVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVectorRequest.ProtoReflect.Descriptor instead.
func (*PutVectorRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{11}
}

func (x *PutVectorRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PutVectorRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *PutVectorRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PutVectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutVectorRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *PutVectorRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PutVectorRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,5,opt,name=k,proto3" json:"k,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	UseAt         bool                   `protobuf:"varint,7,opt,name=use_at,json=useAt,proto3" json:"use_at,omitempty"`
	AtLamport     uint64                 `protobuf:"varint,8,opt,name=at_lamport,json=atLamport,proto3" json:"at_lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SearchRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetUseAt() bool {
	if x != nil {
		return x.UseAt
	}
	return false
}

func (x *SearchRequest) GetAtLamport() uint64 {
	if x != nil {
		return x.AtLamport
	}
	return 0
}

type SearchVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         []float32              `protobuf:"fixed32,4,rep,packed,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,5,opt,name=k,proto3" json:"k,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	UseAt         bool                   `protobuf:"varint,7,opt,name=use_at,json=useAt,proto3" json:"use_at,omitempty"`
	AtLamport     uint64                 `protobuf:"varint,8,opt,name=at_lamport,json=atLamport,proto3" json:"at_lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVectorRequest) Reset() {
	*x = SearchVectorRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorRequest) ProtoMessage() {}

func (x *SearchVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorRequest.ProtoReflect.Descriptor instead.
func (*SearchVectorRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{14}
}

func (x *SearchVectorRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SearchVectorRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *SearchVectorRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchVectorRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchVectorRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchVectorRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchVectorRequest) GetUseAt() bool {
	if x != nil {
		return x.UseAt
	}
	return false
}

func (x *SearchVectorRequest) GetAtLamport() uint64 {
	if x != nil {
		return x.AtLamport
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_corkscrewdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Internal      bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	UseAt         bool                   `protobuf:"varint,5,opt,name=use_at,json=useAt,proto3" json:"use_at,omitempty"`
	AtLamport     uint64                 `protobuf:"varint,6,opt,name=at_lamport,json=atLamport,proto3" json:"at_lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{16}
}

func (x *HistoryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HistoryRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *HistoryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *HistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryRequest) GetUseAt() bool {
	if x != nil {
		return x.UseAt
	}
	return false
}

func (x *HistoryRequest) GetAtLamport() uint64 {
	if x != nil {
		return x.AtLamport
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Version             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_corkscrewdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{17}
}

func (x *HistoryResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type PullEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	SinceClock    uint64                 `protobuf:"varint,3,opt,name=since_clock,json=sinceClock,proto3" json:"since_clock,omitempty"`
	MaxEntries    int32                  `protobuf:"varint,4,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEntriesRequest) Reset() {
	*x = PullEntriesRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEntriesRequest) ProtoMessage() {}

func (x *PullEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEntriesRequest.ProtoReflect.Descriptor instead.
func (*PullEntriesRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{18}
}

func (x *PullEntriesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PullEntriesRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PullEntriesRequest) GetSinceClock() uint64 {
	if x != nil {
		return x.SinceClock
	}
	return 0
}

func (x *PullEntriesRequest) GetMaxEntries() int32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type ReplicaEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          uint32                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	VectorId      string                 `protobuf:"bytes,3,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LamportClock  uint64                 `protobuf:"varint,7,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	ActorId       string                 `protobuf:"bytes,8,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	WallClock     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=wall_clock,json=wallClock,proto3" json:"wall_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaEntry) Reset() {
	*x = ReplicaEntry{}
	mi := &file_corkscrewdb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaEntry) ProtoMessage() {}

func (x *ReplicaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaEntry.ProtoReflect.Descriptor instead.
func (*ReplicaEntry) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{19}
}

func (x *ReplicaEntry) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ReplicaEntry) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ReplicaEntry) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *ReplicaEntry) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *ReplicaEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplicaEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReplicaEntry) GetLamportClock() uint64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *ReplicaEntry) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ReplicaEntry) GetWallClock() *timestamppb.Timestamp {
	if x != nil {
		return x.WallClock
	}
	return nil
}

type PullEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReplicaEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	LatestClock   uint64                 `protobuf:"varint,2,opt,name=latest_clock,json=latestClock,proto3" json:"latest_clock,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEntriesResponse) Reset() {
	*x = PullEntriesResponse{}
	mi := &file_corkscrewdb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEntriesResponse) ProtoMessage() {}

func (x *PullEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEntriesResponse.ProtoReflect.Descriptor instead.
func (*PullEntriesResponse) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{20}
}

func (x *PullEntriesResponse) GetEntries() []*ReplicaEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PullEntriesResponse) GetLatestClock() uint64 {
	if x != nil {
		return x.LatestClock
	}
	return 0
}

func (x *PullEntriesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type PullSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullSnapshotRequest) Reset() {
	*x = PullSnapshotRequest{}
	mi := &file_corkscrewdb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSnapshotRequest) ProtoMessage() {}

func (x *PullSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PullSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{21}
}

func (x *PullSnapshotRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PullSnapshotRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type SnapshotVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LamportClock  uint64                 `protobuf:"varint,4,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	WallClock     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=wall_clock,json=wallClock,proto3" json:"wall_clock,omitempty"`
	Tombstone     bool                   `protobuf:"varint,7,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotVersion) Reset() {
	*x = SnapshotVersion{}
	mi := &file_corkscrewdb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotVersion) ProtoMessage() {}

func (x *SnapshotVersion) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotVersion.ProtoReflect.Descriptor instead.
func (*SnapshotVersion) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{22}
}

func (x *SnapshotVersion) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SnapshotVersion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SnapshotVersion) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SnapshotVersion) GetLamportClock() uint64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *SnapshotVersion) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SnapshotVersion) GetWallClock() *timestamppb.Timestamp {
	if x != nil {
		return x.WallClock
	}
	return nil
}

func (x *SnapshotVersion) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type SnapshotRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Versions      []*SnapshotVersion     `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRecord) Reset() {
	*x = SnapshotRecord{}
	mi := &file_corkscrewdb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecord) ProtoMessage() {}

func (x *SnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecord.ProtoReflect.Descriptor instead.
func (*SnapshotRecord) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{23}
}

func (x *SnapshotRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotRecord) GetVersions() []*SnapshotVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type PullSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	BitWidth      int32                  `protobuf:"varint,2,opt,name=bit_width,json=bitWidth,proto3" json:"bit_width,omitempty"`
	Seed          int64                  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	Dim           int32                  `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	MaxLamport    uint64                 `protobuf:"varint,5,opt,name=max_lamport,json=maxLamport,proto3" json:"max_lamport,omitempty"`
	Records       []*SnapshotRecord      `protobuf:"bytes,6,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullSnapshotResponse) Reset() {
	*x = PullSnapshotResponse{}
	mi := &file_corkscrewdb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSnapshotResponse) ProtoMessage() {}

func (x *PullSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corkscrewdb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PullSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_corkscrewdb_proto_rawDescGZIP(), []int{24}
}

func (x *PullSnapshotResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PullSnapshotResponse) GetBitWidth() int32 {
	if x != nil {
		return x.BitWidth
	}
	return 0
}

func (x *PullSnapshotResponse) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *PullSnapshotResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *PullSnapshotResponse) GetMaxLamport() uint64 {
	if x != nil {
		return x.MaxLamport
	}
	return 0
}

func (x *PullSnapshotResponse) GetRecords() []*SnapshotRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_corkscrewdb_proto protoreflect.FileDescriptor

const file_corkscrewdb_proto_rawDesc = "" +
	"\n" +
	"\x11corkscrewdb.proto\x12\x18corkscrewdb.transport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"3\n" +
	"\x0fEmbeddingConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\"\xbb\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.corkscrewdb.transport.v1.Entry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x06Filter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xf1\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12P\n" +
	"\bmetadata\x18\x04 \x03(\v24.corkscrewdb.transport.v1.SearchResult.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x02\n" +
	"\aVersion\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.corkscrewdb.transport.v1.Version.MetadataEntryR\bmetadata\x12#\n" +
	"\rlamport_clock\x18\x04 \x01(\x04R\flamportClock\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"wall_clock\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\twallClock\x12\x1c\n" +
	"\ttombstone\x18\a \x01(\bR\ttombstone\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\vInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x96\x01\n" +
	"\fInfoResponse\x12'\n" +
	"\x0fpackage_version\x18\x01 \x01(\tR\x0epackageVersion\x12G\n" +
	"\tembedding\x18\x02 \x01(\v2).corkscrewdb.transport.v1.EmbeddingConfigR\tembedding\x12\x14\n" +
	"\x05peers\x18\x03 \x03(\tR\x05peers\"`\n" +
	"\x17EnsureCollectionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbit_width\x18\x03 \x01(\x05R\bbitWidth\"A\n" +
	"\x15DropCollectionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa5\x01\n" +
	"\n" +
	"PutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x125\n" +
	"\x05entry\x18\x05 \x01(\v2\x1f.corkscrewdb.transport.v1.EntryR\x05entry\"\xb3\x02\n" +
	"\x10PutVectorRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x05 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12T\n" +
	"\bmetadata\x18\a \x03(\v28.corkscrewdb.transport.v1.PutVectorRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\xf7\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x05 \x01(\x05R\x01k\x12:\n" +
	"\afilters\x18\x06 \x03(\v2 .corkscrewdb.transport.v1.FilterR\afilters\x12\x15\n" +
	"\x06use_at\x18\a \x01(\bR\x05useAt\x12\x1d\n" +
	"\n" +
	"at_lamport\x18\b \x01(\x04R\tatLamport\"\xfd\x01\n" +
	"\x13SearchVectorRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x04 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x05 \x01(\x05R\x01k\x12:\n" +
	"\afilters\x18\x06 \x03(\v2 .corkscrewdb.transport.v1.FilterR\afilters\x12\x15\n" +
	"\x06use_at\x18\a \x01(\bR\x05useAt\x12\x1d\n" +
	"\n" +
	"at_lamport\x18\b \x01(\x04R\tatLamport\"R\n" +
	"\x0eSearchResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.corkscrewdb.transport.v1.SearchResultR\aresults\"\xa8\x01\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x15\n" +
	"\x06use_at\x18\x05 \x01(\bR\x05useAt\x12\x1d\n" +
	"\n" +
	"at_lamport\x18\x06 \x01(\x04R\tatLamport\"P\n" +
	"\x0fHistoryResponse\x12=\n" +
	"\bversions\x18\x01 \x03(\v2!.corkscrewdb.transport.v1.VersionR\bversions\"\x8c\x01\n" +
	"\x12PullEntriesRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vsince_clock\x18\x03 \x01(\x04R\n" +
	"sinceClock\x12\x1f\n" +
	"\vmax_entries\x18\x04 \x01(\x05R\n" +
	"maxEntries\"\xa0\x03\n" +
	"\fReplicaEntry\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\tvector_id\x18\x03 \x01(\tR\bvectorId\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12P\n" +
	"\bmetadata\x18\x06 \x03(\v24.corkscrewdb.transport.v1.ReplicaEntry.MetadataEntryR\bmetadata\x12#\n" +
	"\rlamport_clock\x18\a \x01(\x04R\flamportClock\x12\x19\n" +
	"\bactor_id\x18\b \x01(\tR\aactorId\x129\n" +
	"\n" +
	"wall_clock\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\twallClock\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x13PullEntriesResponse\x12@\n" +
	"\aentries\x18\x01 \x03(\v2&.corkscrewdb.transport.v1.ReplicaEntryR\aentries\x12!\n" +
	"\flatest_clock\x18\x02 \x01(\x04R\vlatestClock\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"K\n" +
	"\x13PullSnapshotRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"\xee\x02\n" +
	"\x0fSnapshotVersion\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12S\n" +
	"\bmetadata\x18\x03 \x03(\v27.corkscrewdb.transport.v1.SnapshotVersion.MetadataEntryR\bmetadata\x12#\n" +
	"\rlamport_clock\x18\x04 \x01(\x04R\flamportClock\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"wall_clock\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\twallClock\x12\x1c\n" +
	"\ttombstone\x18\a \x01(\bR\ttombstone\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x0eSnapshotRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\bversions\x18\x02 \x03(\v2).corkscrewdb.transport.v1.SnapshotVersionR\bversions\"\xde\x01\n" +
	"\x14PullSnapshotResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1b\n" +
	"\tbit_width\x18\x02 \x01(\x05R\bbitWidth\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\x05R\x03dim\x12\x1f\n" +
	"\vmax_lamport\x18\x05 \x01(\x04R\n" +
	"maxLamport\x12B\n" +
	"\arecords\x18\x06 \x03(\v2(.corkscrewdb.transport.v1.SnapshotRecordR\arecords2\xad\b\n" +
	"\vCorkScrewDB\x12U\n" +
	"\x04Info\x12%.corkscrewdb.transport.v1.InfoRequest\x1a&.corkscrewdb.transport.v1.InfoResponse\x12f\n" +
	"\x10EnsureCollection\x121.corkscrewdb.transport.v1.EnsureCollectionRequest\x1a\x1f.corkscrewdb.transport.v1.Empty\x12b\n" +
	"\x0eDropCollection\x12/.corkscrewdb.transport.v1.DropCollectionRequest\x1a\x1f.corkscrewdb.transport.v1.Empty\x12L\n" +
	"\x03Put\x12$.corkscrewdb.transport.v1.PutRequest\x1a\x1f.corkscrewdb.transport.v1.Empty\x12X\n" +
	"\tPutVector\x12*.corkscrewdb.transport.v1.PutVectorRequest\x1a\x1f.corkscrewdb.transport.v1.Empty\x12R\n" +
	"\x06Delete\x12'.corkscrewdb.transport.v1.DeleteRequest\x1a\x1f.corkscrewdb.transport.v1.Empty\x12[\n" +
	"\x06Search\x12'.corkscrewdb.transport.v1.SearchRequest\x1a(.corkscrewdb.transport.v1.SearchResponse\x12g\n" +
	"\fSearchVector\x12-.corkscrewdb.transport.v1.SearchVectorRequest\x1a(.corkscrewdb.transport.v1.SearchResponse\x12^\n" +
	"\aHistory\x12(.corkscrewdb.transport.v1.HistoryRequest\x1a).corkscrewdb.transport.v1.HistoryResponse\x12j\n" +
	"\vPullEntries\x12,.corkscrewdb.transport.v1.PullEntriesRequest\x1a-.corkscrewdb.transport.v1.PullEntriesResponse\x12m\n" +
	"\fPullSnapshot\x12-.corkscrewdb.transport.v1.PullSnapshotRequest\x1a..corkscrewdb.transport.v1.PullSnapshotResponseB/Z-github.com/odvcencio/corkscrewdb/grpc;grpcapib\x06proto3"

var (
	file_corkscrewdb_proto_rawDescOnce sync.Once
	file_corkscrewdb_proto_rawDescData []byte
)

func file_corkscrewdb_proto_rawDescGZIP() []byte {
	file_corkscrewdb_proto_rawDescOnce.Do(func() {
		file_corkscrewdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corkscrewdb_proto_rawDesc), len(file_corkscrewdb_proto_rawDesc)))
	})
	return file_corkscrewdb_proto_rawDescData
}

var file_corkscrewdb_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_corkscrewdb_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: corkscrewdb.transport.v1.Empty
	(*EmbeddingConfig)(nil),         // 1: corkscrewdb.transport.v1.EmbeddingConfig
	(*Entry)(nil),                   // 2: corkscrewdb.transport.v1.Entry
	(*Filter)(nil),                  // 3: corkscrewdb.transport.v1.Filter
	(*SearchResult)(nil),            // 4: corkscrewdb.transport.v1.SearchResult
	(*Version)(nil),                 // 5: corkscrewdb.transport.v1.Version
	(*InfoRequest)(nil),             // 6: corkscrewdb.transport.v1.InfoRequest
	(*InfoResponse)(nil),            // 7: corkscrewdb.transport.v1.InfoResponse
	(*EnsureCollectionRequest)(nil), // 8: corkscrewdb.transport.v1.EnsureCollectionRequest
	(*DropCollectionRequest)(nil),   // 9: corkscrewdb.transport.v1.DropCollectionRequest
	(*PutRequest)(nil),              // 10: corkscrewdb.transport.v1.PutRequest
	(*PutVectorRequest)(nil),        // 11: corkscrewdb.transport.v1.PutVectorRequest
	(*DeleteRequest)(nil),           // 12: corkscrewdb.transport.v1.DeleteRequest
	(*SearchRequest)(nil),           // 13: corkscrewdb.transport.v1.SearchRequest
	(*SearchVectorRequest)(nil),     // 14: corkscrewdb.transport.v1.SearchVectorRequest
	(*SearchResponse)(nil),          // 15: corkscrewdb.transport.v1.SearchResponse
	(*HistoryRequest)(nil),          // 16: corkscrewdb.transport.v1.HistoryRequest
	(*HistoryResponse)(nil),         // 17: corkscrewdb.transport.v1.HistoryResponse
	(*PullEntriesRequest)(nil),      // 18: corkscrewdb.transport.v1.PullEntriesRequest
	(*ReplicaEntry)(nil),            // 19: corkscrewdb.transport.v1.ReplicaEntry
	(*PullEntriesResponse)(nil),     // 20: corkscrewdb.transport.v1.PullEntriesResponse
	(*PullSnapshotRequest)(nil),     // 21: corkscrewdb.transport.v1.PullSnapshotRequest
	(*SnapshotVersion)(nil),         // 22: corkscrewdb.transport.v1.SnapshotVersion
	(*SnapshotRecord)(nil),          // 23: corkscrewdb.transport.v1.SnapshotRecord
	(*PullSnapshotResponse)(nil),    // 24: corkscrewdb.transport.v1.PullSnapshotResponse
	nil,                             // 25: corkscrewdb.transport.v1.Entry.MetadataEntry
	nil,                             // 26: corkscrewdb.transport.v1.SearchResult.MetadataEntry
	nil,                             // 27: corkscrewdb.transport.v1.Version.MetadataEntry
	nil,                             // 28: corkscrewdb.transport.v1.PutVectorRequest.MetadataEntry
	nil,                             // 29: corkscrewdb.transport.v1.ReplicaEntry.MetadataEntry
	nil,                             // 30: corkscrewdb.transport.v1.SnapshotVersion.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 31: google.protobuf.Timestamp
}
var file_corkscrewdb_proto_depIdxs = []int32{
	25, // 0: corkscrewdb.transport.v1.Entry.metadata:type_name -> corkscrewdb.transport.v1.Entry.MetadataEntry
	26, // 1: corkscrewdb.transport.v1.SearchResult.metadata:type_name -> corkscrewdb.transport.v1.SearchResult.MetadataEntry
	27, // 2: corkscrewdb.transport.v1.Version.metadata:type_name -> corkscrewdb.transport.v1.Version.MetadataEntry
	31, // 3: corkscrewdb.transport.v1.Version.wall_clock:type_name -> google.protobuf.Timestamp
	1,  // 4: corkscrewdb.transport.v1.InfoResponse.embedding:type_name -> corkscrewdb.transport.v1.EmbeddingConfig
	2,  // 5: corkscrewdb.transport.v1.PutRequest.entry:type_name -> corkscrewdb.transport.v1.Entry
	28, // 6: corkscrewdb.transport.v1.PutVectorRequest.metadata:type_name -> corkscrewdb.transport.v1.PutVectorRequest.MetadataEntry
	3,  // 7: corkscrewdb.transport.v1.SearchRequest.filters:type_name -> corkscrewdb.transport.v1.Filter
	3,  // 8: corkscrewdb.transport.v1.SearchVectorRequest.filters:type_name -> corkscrewdb.transport.v1.Filter
	4,  // 9: corkscrewdb.transport.v1.SearchResponse.results:type_name -> corkscrewdb.transport.v1.SearchResult
	5,  // 10: corkscrewdb.transport.v1.HistoryResponse.versions:type_name -> corkscrewdb.transport.v1.Version
	29, // 11: corkscrewdb.transport.v1.ReplicaEntry.metadata:type_name -> corkscrewdb.transport.v1.ReplicaEntry.MetadataEntry
	31, // 12: corkscrewdb.transport.v1.ReplicaEntry.wall_clock:type_name -> google.protobuf.Timestamp
	19, // 13: corkscrewdb.transport.v1.PullEntriesResponse.entries:type_name -> corkscrewdb.transport.v1.ReplicaEntry
	30, // 14: corkscrewdb.transport.v1.SnapshotVersion.metadata:type_name -> corkscrewdb.transport.v1.SnapshotVersion.MetadataEntry
	31, // 15: corkscrewdb.transport.v1.SnapshotVersion.wall_clock:type_name -> google.protobuf.Timestamp
	22, // 16: corkscrewdb.transport.v1.SnapshotRecord.versions:type_name -> corkscrewdb.transport.v1.SnapshotVersion
	23, // 17: corkscrewdb.transport.v1.PullSnapshotResponse.records:type_name -> corkscrewdb.transport.v1.SnapshotRecord
	6,  // 18: corkscrewdb.transport.v1.CorkScrewDB.Info:input_type -> corkscrewdb.transport.v1.InfoRequest
	8,  // 19: corkscrewdb.transport.v1.CorkScrewDB.EnsureCollection:input_type -> corkscrewdb.transport.v1.EnsureCollectionRequest
	9,  // 20: corkscrewdb.transport.v1.CorkScrewDB.DropCollection:input_type -> corkscrewdb.transport.v1.DropCollectionRequest
	10, // 21: corkscrewdb.transport.v1.CorkScrewDB.Put:input_type -> corkscrewdb.transport.v1.PutRequest
	11, // 22: corkscrewdb.transport.v1.CorkScrewDB.PutVector:input_type -> corkscrewdb.transport.v1.PutVectorRequest
	12, // 23: corkscrewdb.transport.v1.CorkScrewDB.Delete:input_type -> corkscrewdb.transport.v1.DeleteRequest
	13, // 24: corkscrewdb.transport.v1.CorkScrewDB.Search:input_type -> corkscrewdb.transport.v1.SearchRequest
	14, // 25: corkscrewdb.transport.v1.CorkScrewDB.SearchVector:input_type -> corkscrewdb.transport.v1.SearchVectorRequest
	16, // 26: corkscrewdb.transport.v1.CorkScrewDB.History:input_type -> corkscrewdb.transport.v1.HistoryRequest
	18, // 27: corkscrewdb.transport.v1.CorkScrewDB.PullEntries:input_type -> corkscrewdb.transport.v1.PullEntriesRequest
	21, // 28: corkscrewdb.transport.v1.CorkScrewDB.PullSnapshot:input_type -> corkscrewdb.transport.v1.PullSnapshotRequest
	7,  // 29: corkscrewdb.transport.v1.CorkScrewDB.Info:output_type -> corkscrewdb.transport.v1.InfoResponse
	0,  // 30: corkscrewdb.transport.v1.CorkScrewDB.EnsureCollection:output_type -> corkscrewdb.transport.v1.Empty
	0,  // 31: corkscrewdb.transport.v1.CorkScrewDB.DropCollection:output_type -> corkscrewdb.transport.v1.Empty
	0,  // 32: corkscrewdb.transport.v1.CorkScrewDB.Put:output_type -> corkscrewdb.transport.v1.Empty
	0,  // 33: corkscrewdb.transport.v1.CorkScrewDB.PutVector:output_type -> corkscrewdb.transport.v1.Empty
	0,  // 34: corkscrewdb.transport.v1.CorkScrewDB.Delete:output_type -> corkscrewdb.transport.v1.Empty
	15, // 35: corkscrewdb.transport.v1.CorkScrewDB.Search:output_type -> corkscrewdb.transport.v1.SearchResponse
	15, // 36: corkscrewdb.transport.v1.CorkScrewDB.SearchVector:output_type -> corkscrewdb.transport.v1.SearchResponse
	17, // 37: corkscrewdb.transport.v1.CorkScrewDB.History:output_type -> corkscrewdb.transport.v1.HistoryResponse
	20, // 38: corkscrewdb.transport.v1.CorkScrewDB.PullEntries:output_type -> corkscrewdb.transport.v1.PullEntriesResponse
	24, // 39: corkscrewdb.transport.v1.CorkScrewDB.PullSnapshot:output_type -> corkscrewdb.transport.v1.PullSnapshotResponse
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_corkscrewdb_proto_init() }
func file_corkscrewdb_proto_init() {
	if File_corkscrewdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corkscrewdb_proto_rawDesc), len(file_corkscrewdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corkscrewdb_proto_goTypes,
		DependencyIndexes: file_corkscrewdb_proto_depIdxs,
		MessageInfos:      file_corkscrewdb_proto_msgTypes,
	}.Build()
	File_corkscrewdb_proto = out.File
	file_corkscrewdb_proto_goTypes = nil
	file_corkscrewdb_proto_depIdxs = nil
}
