apiVersion: v1
kind: Service
metadata:
  name: memory
  namespace: m31labs
  labels:
    app: memory
spec:
  type: ClusterIP
  selector:
    app: memory
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
