apiVersion: v1
kind: Service
metadata:
  name: corkscrewdb-ro
  namespace: m31labs
  labels:
    app: corkscrewdb
    role: ro
spec:
  type: ClusterIP
  selector:
    app: corkscrewdb
  ports:
    - name: grpc
      port: 4040
      targetPort: 4040
      protocol: TCP
